import enum, uuid
from datetime import datetime
from sqlalchemy import DateTime, Enum, ForeignKey, Index, String, UniqueConstraint, Uuid
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, TimestampMixin

class CalendarConnectionStatus(str, enum.Enum): CONNECTED="connected"; REAUTHORIZATION_REQUIRED="reauthorization_required"; DISCONNECTED="disconnected"
class CalendarSyncStatus(str, enum.Enum): PENDING="pending"; PROCESSING="processing"; SENT="sent"; RETRY_SCHEDULED="retry_scheduled"; PERMANENTLY_FAILED="permanently_failed"; CANCELLED="cancelled"
class CalendarOperation(str, enum.Enum): CREATE="create"; UPDATE="update"; DELETE="delete"
def values(e): return [x.value for x in e]
class GoogleCalendarConnection(TimestampMixin, Base):
 __tablename__="google_calendar_connections"; id: Mapped[uuid.UUID]=mapped_column(Uuid, primary_key=True, default=uuid.uuid4); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),unique=True,nullable=False); access_token_encrypted: Mapped[str]=mapped_column(String,nullable=False); refresh_token_encrypted: Mapped[str|None]=mapped_column(String); token_expiry: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); scopes: Mapped[str]=mapped_column(String(1000),nullable=False); calendar_id: Mapped[str]=mapped_column(String(255),default="primary",nullable=False); status: Mapped[CalendarConnectionStatus]=mapped_column(Enum(CalendarConnectionStatus,name="calendar_connection_status",values_callable=values,native_enum=False,length=40),nullable=False); disconnected_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class GoogleOAuthState(Base):
 __tablename__="google_oauth_states"; id: Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); state_hash: Mapped[str]=mapped_column(String(64),unique=True,nullable=False); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),nullable=False); redirect_destination: Mapped[str]=mapped_column(String(100),nullable=False); expires_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); consumed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class CalendarSyncJob(TimestampMixin,Base):
 __tablename__="calendar_sync_jobs"; __table_args__=(UniqueConstraint("idempotency_key"),Index("ix_calendar_sync_due","status","next_attempt_at")); id: Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); appointment_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("appointments.id",ondelete="CASCADE"),nullable=False); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),nullable=False); operation: Mapped[CalendarOperation]=mapped_column(Enum(CalendarOperation,name="calendar_operation",values_callable=values,native_enum=False,length=20),nullable=False); idempotency_key: Mapped[str]=mapped_column(String(255),nullable=False); status: Mapped[CalendarSyncStatus]=mapped_column(Enum(CalendarSyncStatus,name="calendar_sync_status",values_callable=values,native_enum=False,length=40),default=CalendarSyncStatus.PENDING,nullable=False); attempt_count: Mapped[int]=mapped_column(default=0,nullable=False); next_attempt_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); claimed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); claimed_by: Mapped[str|None]=mapped_column(String(120)); failure_category: Mapped[str|None]=mapped_column(String(80)); failure_message: Mapped[str|None]=mapped_column(String(255))
class AppointmentCalendarMapping(TimestampMixin,Base):
 __tablename__="appointment_calendar_mappings"; __table_args__=(UniqueConstraint("appointment_id","user_id","calendar_id",name="uq_calendar_mapping_appointment_user_calendar"),Index("ix_calendar_mapping_appointment","appointment_id")); id: Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); appointment_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("appointments.id",ondelete="CASCADE"),nullable=False); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),nullable=False); connection_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("google_calendar_connections.id",ondelete="CASCADE"),nullable=False); calendar_id: Mapped[str]=mapped_column(String(255),nullable=False); google_event_id: Mapped[str|None]=mapped_column(String(255)); last_synced_version: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); sync_status: Mapped[str]=mapped_column(String(40),nullable=False); failure_category: Mapped[str|None]=mapped_column(String(80)); failure_message: Mapped[str|None]=mapped_column(String(255)); last_synced_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
