"""google calendar connection state and durable sync jobs"""
from alembic import op
import sqlalchemy as sa
revision="20260822_07"; down_revision="20260822_06"; branch_labels=None; depends_on=None
def upgrade():
 op.create_table("google_calendar_connections",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="CASCADE"),unique=True),sa.Column("access_token_encrypted",sa.String(),nullable=False),sa.Column("refresh_token_encrypted",sa.String()),sa.Column("token_expiry",sa.DateTime(timezone=True)),sa.Column("scopes",sa.String(1000),nullable=False),sa.Column("calendar_id",sa.String(255),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("disconnected_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("google_oauth_states",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("state_hash",sa.String(64),unique=True),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="CASCADE")),sa.Column("redirect_destination",sa.String(100),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("consumed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("calendar_sync_jobs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("appointment_id",sa.Uuid(),sa.ForeignKey("appointments.id",ondelete="CASCADE")),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="CASCADE")),sa.Column("operation",sa.String(20),nullable=False),sa.Column("idempotency_key",sa.String(255),unique=True),sa.Column("status",sa.String(40),nullable=False),sa.Column("attempt_count",sa.Integer(),nullable=False),sa.Column("next_attempt_at",sa.DateTime(timezone=True),nullable=False),sa.Column("claimed_at",sa.DateTime(timezone=True)),sa.Column("claimed_by",sa.String(120)),sa.Column("failure_category",sa.String(80)),sa.Column("failure_message",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_calendar_sync_due","calendar_sync_jobs",["status","next_attempt_at"])
 op.create_table("appointment_calendar_mappings",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("appointment_id",sa.Uuid(),sa.ForeignKey("appointments.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("connection_id",sa.Uuid(),sa.ForeignKey("google_calendar_connections.id",ondelete="CASCADE"),nullable=False),sa.Column("calendar_id",sa.String(255),nullable=False),sa.Column("google_event_id",sa.String(255)),sa.Column("last_synced_version",sa.DateTime(timezone=True)),sa.Column("sync_status",sa.String(40),nullable=False),sa.Column("failure_category",sa.String(80)),sa.Column("failure_message",sa.String(255)),sa.Column("last_synced_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("appointment_id","user_id","calendar_id",name="uq_calendar_mapping_appointment_user_calendar"));op.create_index("ix_calendar_mapping_appointment","appointment_calendar_mappings",["appointment_id"])
def downgrade(): op.drop_index("ix_calendar_mapping_appointment",table_name="appointment_calendar_mappings");op.drop_table("appointment_calendar_mappings");op.drop_index("ix_calendar_sync_due",table_name="calendar_sync_jobs");op.drop_table("calendar_sync_jobs");op.drop_table("google_oauth_states");op.drop_table("google_calendar_connections")
