import { useState, type FormEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { FormField } from "../components/FormField";

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const token = params.get("token") || ""; const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState(token ? "" : "This password-reset link is invalid or has expired."); const [pending, setPending] = useState(false); const [success, setSuccess] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password !== confirmation) { setError("Passwords do not match."); return; } setPending(true); setError(""); try { await api.resetPassword(token, password, confirmation); window.history.replaceState({}, "", "/reset-password"); setSuccess(true); setTimeout(() => navigate("/login", { state: { notice: "Password reset complete. Please sign in." } }), 800); } catch { setError("This password-reset link is invalid or has expired."); } finally { setPending(false); } };
  return <div className="mx-auto max-w-md px-5 py-14"><div className="ui-card p-7 shadow-lift sm:p-9"><Link className="text-sm font-semibold text-care-700 hover:underline" to="/login">← Return to sign in</Link><h1 className="mt-5 text-3xl font-bold">Choose a new password</h1>{success ? <p className="ui-alert-success mt-5">Password reset complete. Redirecting to sign in…</p> : <form className="mt-6 space-y-5" onSubmit={submit}>{error && <p className="ui-alert-error" role="alert">{error}</p>}<FormField id="new-password" label="New password" type="password" value={password} autoComplete="new-password" onChange={setPassword}/><FormField id="confirm-password" label="Confirm new password" type="password" value={confirmation} autoComplete="new-password" onChange={setConfirmation}/><p className="text-xs text-slate-500">At least 10 characters with uppercase, lowercase, and a number.</p><button className="ui-button-primary w-full" disabled={pending || !token}>{pending ? "Resetting…" : "Reset password"}</button></form>}</div></div>;
}
